before:
  hooks:
  - go mod download

builds:
  - id: "haqqd-darwin"
    main: ./cmd/haqqd
    binary: bin/haqqd
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
